name: Dependency Update

on:
  schedule:
    - cron: '0 9 * * 1' # Weekly on Monday at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Update dependencies
        run: |
          bun update
          bun install
      
      - name: Run tests
        run: bun test
        continue-on-error: true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: weekly dependency updates'
          body: |
            ## Weekly Dependency Updates
            
            This PR contains the latest dependency updates.
            
            ### Changes
            - Updated dependencies to their latest versions
            - Regenerated lockfile
            
            ### Checklist
            - [ ] Tests pass
            - [ ] No breaking changes identified
            - [ ] Security vulnerabilities addressed
            
            Please review the changes and merge if everything looks good.
          branch: deps/weekly-update
          delete-branch: true
          labels: |
            dependencies
            automated