name: Deploy to Fly.io

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run tests
        run: bun test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: Check deployment status
        run: flyctl status
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: Monitor deployment health
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30
          flyctl status --json | jq '.Allocations[] | select(.Status != "running")' > failed_allocs.json
          if [ -s failed_allocs.json ]; then
            echo "Failed allocations detected:"
            cat failed_allocs.json
            exit 1
          fi
          echo "All allocations healthy!"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}